
###
# Test case where multiple robots are within 10 units
POST http://localhost:5000/api/robots/closest/
Content-Type: application/json

{
  "loadId": 231,
  "x": 20,
  "y": 20
}

###
# Test case where no robots are within 10 units
POST http://localhost:5000/api/robots/closest/
Content-Type: application/json

{
  "loadId": 231,
  "x": 999,
  "y": 999
}

###
# Test case where only a single robot is within 10 units
POST http://localhost:5000/api/robots/closest/
Content-Type: application/json

{
  "loadId": 231,
  "x": 0,
  "y": 0
}

